###
# Create a new post
POST http://localhost:3000/post
Content-Type: application/json

{
  "sender": "JohnDoe222",
  "content": "asdasdsdads"
}


###
# Get all posts
GET http://localhost:3000/post


###
# Get posts by sender
GET http://localhost:3000/post?sender=JohnDoe


###
# Get post by ID
GET http://localhost:3000/post/{{postId}}


###
# Update post
PUT http://localhost:3000/post/{{postId}}
Content-Type: application/json

{
  "sender": "JohnDoe",
  "content": "Updated content!"
}


###
# Delete post
DELETE http://localhost:3000/post/{{postId}}


###
# Create a new comment
POST http://localhost:3000/comment
Content-Type: application/json

{
  "postId": "{{postId}}",
  "sender": "JaneDoe",
  "content": "Great post!"
}


###
# Get all comments
GET http://localhost:3000/comment


###
# Get comments by sender
GET http://localhost:3000/comment?sender=JohnDoe


###
# Get comments by post ID
GET http://localhost:3000/comment?postId={{postId}}


###
# Get comment by ID
GET http://localhost:3000/comment/{{commentId}}


###
# Update comment
PUT http://localhost:3000/comment/{{commentId}}
Content-Type: application/json

{
  "content": "Updated comment content!"
}


###
# Delete comment
DELETE http://localhost:3000/comment/{{commentId}}
